show_selection_mark = false
capture_mosue = false

[special-paths]
"/nix" = {list = "never", show = "never", sum = "never"}

[[verbs]]
key = "ctrl-o"
external = "footclient -N nvim {file}"
leave_broot = false
shortcut = "o"
switch_terminal = false

[[verbs]]
key = "ctrl-e"
external = "nvim {file}"
leave_broot = false
switch_terminal = false

[[verbs]]
invocation = "open_new {path}"
shortcut = "on"
external = "footclient -N nvim {directory}/{path}"
leave_broot = false
switch_terminal = false

[[verbs]]
invocation = "edit_new {path}"
shortcut = "en"
external = "nvim {directory}/{path}"
leave_broot = false
switch_terminal = false

[[verbs]]
key = "ctrl-t"
external = "sh"
leave_broot = false

[[verbs]]
key = "ctrl-r"
external = "footclient -N sh"
leave_broot = false
switch_terminal = false

# [search_modes]
# "<empty>" = "fuzzy path"
# "/" = "fuzzy name"

# shallow view
# copy_line, copy_path
# next_dir
# next_same_depth
# open_stay
# stage, stage_all_files
# toggle_files
# ctrl g
# input_del_word_left
# :fo <location>
# running from a socket
# https://dystroy.org/broot/remote/
